#version: '3'
#services:
#  zookeeper:
#    image: wurstmeister/zookeeper
#    platform: linux/amd64  # Ensure compatibility
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#
#  kafka:
#    image: wurstmeister/kafka
#    platform: linux/amd64  # Ensure compatibility
#    container_name: kafka
#    ports:
#      - "9092:9092"
#    environment:
#      - KAFKA_BROKER_ID=1
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092  # ✅ Required
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092  # ✅ Required
#      - KAFKA_LOG_RETENTION_HOURS=168  # 7 days retention
#      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true  # Auto-create topics
#    depends_on:
#      - zookeeper
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock  # Needed for Wurstmeister
